### ISSUE TITLE
dair_v2x_v_dataset

### ISSUE THREAD

**Issue by xpzbph** [huahuasousou/dair_v2x_i_dataset_vis#3]
Hi, thank you for your great work,,I would like to ask if the dair_v2x_v dataset can also be converted in this way? Just by changing the corresponding file names in the program?

**Comment by ysy200187** [comment]
> 我想



> Hi, thank you for your great work,,I would like to ask if the dair_v2x_v dataset can also be converted in this way? Just by changing the corresponding file names in the program?

May I ask if it's possible
